<?php
/**
 * Copyright © ViaBill. All rights reserved.
 * See LICENSE.txt for license details.
 */

/**
 * @var \Viabillhq\Payment\Block\Adminhtml\System\Config\CredentialsForm $block
 */
$myViabillUrl = $block->getMyViaBillUrl();
?>
<div class="pp-buttons-container" id="viabill-request-form">
    <div dir="ltr" class="viabill-buttons" trbidi="on">
        <script type="text/x-magento-init">
            {
                "#viabill-request-form": {
                    "Viabillhq_Payment/js/viabill_request": {
                        "registerForm": "#viabil-register-btn",
                        "registerUrl": "<?= $block->escapeUrl($block->getCredentialsRequestUrl())?>",
                        "registerParam": "<?= $block->escapeJs($block->getCommand())?>"
                    }
                }
            }
        </script>

        <?php if (!empty($myViabillUrl)): ?>
            <a id="viabil-my-viabill-btn" class="my-viabill-btn" 
            href="<?= $block->escapeUrl($myViabillUrl)?>" target="_blank">
                <?= $block->escapeHtml(__('Go to My Viabill')) ?>
            </a>
        <?php endif; ?>

        <?php if ($block->isButtonVisible()): ?>
        <p class="terms-and-conditions-wrap">
            <?php $termsAndConditionLink = $block->escapeUrl($block->getTermsAndConditionsUrl()) ?>

            <input type="checkbox" id="viabil-terms-and-conditions-checkbox" name="terms-and-conditions">
            <label for="viabil-terms-and-conditions-checkbox">
                <span><?= $block->escapeHtml(__("I've read and accept the")) ?> </span>
                <a data-link="<?= $block->escapeUrl($termsAndConditionLink) ?>" 
                id="viabil-terms-and-conditions-link" 
                href="<?= $block->escapeUrl($termsAndConditionLink) ?>" target="_blank">
                    <?= $block->escapeHtml(__('terms & conditions')) ?>
                </a>
            </label>
        </p>

        <span id="viabil-register-btn" class="register-btn action-default disabled">
            <?= $block->escapeHtml(__('Create new user')) ?>
        </span>
        <?php endif; ?>
    </div>
</div>
