<?php

// @codingStandardsIgnoreFile

?>
<?php
/**
 * @see \Viabillhq\Payment\Block\Page\Notices
 */
?>
<?php if ($block->displayTestTransactionNotice()): ?>
    <div class="messages">
        <div class="message message-warning message-demo-mode">
            <?= /* @escapeNotVerified */ __(
                'ViaBill is currently set to Test Mode. ' .
                 'All orders placed with ViaBill should not be shipped! ' .
                 'Remember to disable Test Mode before offering ViaBill on your store.'
            ) ?>
        </div>
    </div>
<?php endif; ?>
